// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "name", type: "string", unique: true },
      { name: "password", type: "string" },
      { name: "email", type: "email", unique: true },
      { name: "userHandle", type: "string" }
    ],
    revLinks: [{ column: "user", table: "items" }],
  },
  {
    name: "items",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "text" },
      { name: "user", type: "link", link: { table: "users" } },
      { name: "created_at", type: "datetime" },
    ],
  },
  {
    name: "credentials",
    columns: [
      { name: "credentialID", type: "string", unique: true },
      { name: "publicKey", type: "text" },
      { name: "counter", type: "int" },
      { name: "userId", type: "link", table: "users" },
      { name: "transports", type: "json" }
    ]
  }
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Items = InferredTypes["items"];
export type ItemsRecord = Items & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  items: ItemsRecord;
};

const DatabaseClient = buildClient();
const defaultOptions = {
  apiKey: import.meta.env.XATA_API_KEY,
  databaseURL: import.meta.env.XATA_DATABASE_URL
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
